function model = LossMeasure(model)

model.LossTrain(model.IdxEpoch) = (-1/model.NumTrain)*((model.YabtTrain*log(model.PabtTrain'))+((1-model.YabtTrain)*log((1-model.PabtTrain')))) ...
                                + (-1/model.NumTrain)*((model.YmtaTrain*log(model.PmtaTrain'))+((1-model.YmtaTrain)*log((1-model.PmtaTrain')))) ...
                                + (-1/model.NumTrain)*((model.YwmhTrain*log(model.PwmhTrain'))+((1-model.YwmhTrain)*log((1-model.PwmhTrain'))));

model.LossValid(model.IdxEpoch) = (-1/model.NumValid)*((model.YabtValid*log(model.PabtValid'))+((1-model.YabtValid)*log((1-model.PabtValid')))) ...
                                + (-1/model.NumValid)*((model.YmtaValid*log(model.PmtaValid'))+((1-model.YmtaValid)*log((1-model.PmtaValid')))) ...
                                + (-1/model.NumValid)*((model.YwmhValid*log(model.PwmhValid'))+((1-model.YwmhValid)*log((1-model.PwmhValid'))));